export const menuItemsData = [
  {
    id: 1,
    name: 'Paderborner [20*0.5 L]',
    info: 'Beer from brewery in Paderborn dating back to 1850s ',
    price: 24,
    img: '/images/beer1.png',
  },
  {
    id: 2,
    name: 'Budweiser [20*0.5L]',
    info: '"King of Beers" as the Americans say ',
    price: 26,
    img: '/images/beer2.png',
  },
  {
    id: 3,
    name: 'Becks [20*0.5L]',
    info: 'Classic German beer from the city of Bremen ',
    price: 24,
    img: '/images/beer3.png',
  },
  {
    id: 4,
    name: 'Corona [6*0.33L]',
    info: 'A special companion to take to the beach from the land of Mexico ',
    price: 16.79,
    img: '/images/beer4.png',
  },
  {
    id: 5,
    name: 'Warsteiner [20*0.5L]',
    info:'Veteran beer as old as 265 years ',
    price: 22,
    img: '/images/beer5.png',
  },
  {
    id: 6,
    name: 'Heineken [20*0.5L]',
    info: 'UEFA Champions League sponsor since 1994 all the way from The Netherlands',
    price: 28,
    img: '/images/beer6.png',
  },
  {
    id: 7,
    name: 'Krombacher [20*0.5L]',
    info: 'Beers fresh from the Krombach region enjoyed around Germany',
    price: 24,
    img: '/images/beer7.png',
  },
  {
    id: 8,
    name: 'Veltins [20*0.5L]',
    info: 'From the western German city of Meschede-Grevenstein, this beer is as refreshing as it gets',
    price: 24,
    img: '/images/beer8.png',
  },
  {
    id: 9,
    name: 'Kolsch [20*0.5L]',
    info: 'Kölsch is a style of beer originating in Cologne, Germany',
    price: 26,
    img: '/images/beer9.png',
  },
  {
    id: 10,
    name: 'Guinness [20*0.33L]',
    info: 'Dark & Bitter Guinness is an Irish dry stout that originates in Ireland. ',
    price: 30,
    img: '/images/beer10.png',
  },
  {
    id: 11,
    name: 'Kingfisher [20*0.33L]',
    info: 'Kingfisher beer is Indias greatest selling beer brand. For the king of good times',
    price: 50,
    img: '/images/beer11.png',
  },
  {
    id: 12,
    name: 'Asahi Super Dry [12*0.33L]',
    info: ' A Japanese rice lager, great companion to along with Sushi. ',
    price: 35,
    img: '/images/beer12.png',
  },
  {
    id: 13,
    name: 'Stella Artois [20*0.5L]',
    info: 'From Leuven, Belgium, this beer is known for its crisp hop bitterness',
    price: 27,
    img: '/images/beer13.png',
  },
  {
    id: 14,
    name: 'Tsingtao [20*0.33L]',
    info: 'The most popular Chinese beer made in Laoshan, a mountain area famous throughout China for the purity of its water',
    price: 38,
    img: '/images/beer14.png',
  },
  {
    id: 15,
    name: 'Kozel [20*0.5L]',
    info: 'From the Czech Republic, Kozel a thick, almost black beer with a dark foam, which makes it feel very strong and masculine',
    price: 22,
    img: '/images/beer15.png',
  }
];
